# Generated by Django 3.2.8 on 2021-10-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=600)),
                ('image1', models.ImageField(blank=True, upload_to='about_image')),
                ('image2', models.ImageField(blank=True, upload_to='about_image')),
                ('image3', models.ImageField(blank=True, upload_to='about_image')),
            ],
        ),
    ]
