# Generated by Django 3.2.8 on 2021-11-03 17:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, upload_to='media')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
