# Generated by Django 3.2.8 on 2022-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='age',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='type',
            field=models.CharField(default='candidate', max_length=15),
        ),
    ]
