# Generated by Django 3.2.8 on 2022-01-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220112_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='date',
            new_name='birthdate',
        ),
    ]
