# Generated by Django 3.2.8 on 2022-01-12 21:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_company_identification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=ckeditor.fields.RichTextField(default='a'),
            preserve_default=False,
        ),
    ]
