# Generated by Django 3.2.8 on 2022-01-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220112_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='type',
            field=models.CharField(default='freelancer', max_length=15),
        ),
    ]
