# Generated by Django 3.2.8 on 2022-01-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_candidate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='status',
        ),
        migrations.AddField(
            model_name='candidate',
            name='conf_number',
            field=models.CharField(default='A', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='conf_number',
            field=models.CharField(default='a', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
