# Generated by Django 3.2.8 on 2022-01-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='verification pending', max_length=20),
        ),
    ]
