# Generated by Django 3.2.8 on 2021-10-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_auto_20211014_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='from_wage_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='to_wage_hour',
            field=models.IntegerField(null=True),
        ),
    ]
