# Generated by Django 3.2.8 on 2021-10-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_auto_20211014_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(default='x', upload_to='company_logos'),
            preserve_default=False,
        ),
    ]
