# Generated by Django 3.2.8 on 2021-10-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0006_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='JobCategory',
        ),
    ]
