# Generated by Django 3.2.8 on 2021-10-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0007_rename_category_jobcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCategory',
        ),
    ]
