# Generated by Django 3.2.8 on 2021-10-17 07:13

from django.db import migrations, models
import django.db.models.deletion
import recruiters.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0009_jobcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(default=recruiters.models.JobCategory.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='recruiters.jobcategory'),
        ),
    ]
