# Generated by Django 3.2.8 on 2021-10-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0010_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
