# Generated by Django 3.2.8 on 2021-10-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0012_jobcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
