# Generated by Django 3.2.8 on 2021-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0014_alter_jobcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/job_category'),
        ),
    ]
