# Generated by Django 3.2.8 on 2021-10-18 10:28

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0016_remove_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='locality',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
