# Generated by Django 3.2.12 on 2022-04-08 20:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_applicant_selected'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_job', to='recruiters.job')),
            ],
            options={
                'verbose_name': 'Saved Jobs',
                'verbose_name_plural': 'Saved Jobs',
            },
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='recruiters.job')),
            ],
            options={
                'verbose_name': 'Applied Jobs',
                'verbose_name_plural': 'Applied Jobs',
            },
        ),
    ]
