# Generated by Django 3.2.8 on 2021-10-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_appliedjobs_savedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Available Countries')),
            ],
        ),
    ]
