# Generated by Django 3.2.12 on 2022-06-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_servicepost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='candidates.category'),
        ),
    ]
